apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-post-deploy-commands
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: cockroachdb-post-deploy-commands-executor
        image: quay.io/AA/BB     # TODO: Change me 
        imagePullPolicy: Always
        env:
          - name: CLUSTER_LIST
            value: {{ .Values.cdbClusters }}
      restartPolicy: OnFailure
  backoffLimit: 2
  