{{- range .Values.cdbClusters }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-post-deploy-commands
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: cockroachdb-post-deploy-commands-executor
        image: quay.io/langley_millard_ibm/patch_cockroach:latest 
        imagePullPolicy: Always
        env:
          - name: CLUSTER_LIST
            value: {{ . }}
      restartPolicy: OnFailure
  backoffLimit: 2
---
{{- end }}