apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  name: vault-intermediate-ca-sync
  namespace: vault
spec:
  clusterDeploymentSelector:
    matchLabels:
      name: azure-cluster-08 
  secretMappings:
    - sourceRef:
        name: vault-intermediate-ca
        namespace: vault 
      targetRef:
        name: rootca
        namespace: vault
