apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  name: vault-ca-sync
spec:
  clusterDeploymentSelector:
    matchLabels:
      cluster.open-cluster-management.io/clusterset: azure-aws-clusterset
  secretMappings:
    - sourceRef:
        name: rootca
        namespace: cert-manager 
      targetRef:
        name: rootca
        namespace: vault
