apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: readiness
        image: quay.io/centos/centos
        args:
        - /bin/sh
        - -c
        - {{ printf "sleep %v; touch /tmp/healthy; sleep 1000000000" .Values.delay }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          periodSeconds: 5
