apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: readiness
        image: quay.io/centos/centos
        args:
        - /bin/sh
        - -c
        - {{ printf "sleep %v; touch /tmp/healthy; sleep 1000000000" .Values.delay }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          periodSeconds: 5
