---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: cockroachdb
  name: cockroachdb-placement-1
  namespace: multi-cluster-cockroachdb
spec:
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: cloud
      operator: In
      values:
      - AWS
    
